name       : ngspice
version    : '36'
release    : 5
source     :
    - https://jztkft.dl.sourceforge.net/project/ngspice/ng-spice-rework/36/ngspice-36.tar.gz : 4f818287efba245341046635b757ae81f879549b326a4316b5f6e697aa517f8c
homepage   : http://ngspice.sourceforge.net/
license    :
    - BSD-3-Clause
    - LGPL-2.1-or-later
component  : office
summary    : Mixed-Level, Mixed-Signal Circuit Simulator
description: |
    Ngspice is a mixed-level/mixed-signal circuit simulator. Its code is based on three open source software packages: Spice3f5, Cider1b1 and Xspice. It is the open source successor of these venerable packages. Many, many modifications, bug fixes and improvements have been added to the code, yielding a stable and reliable simulator. Therefore, besides being used as a standalone simulator, Ngspice has been incorporated into many projects.
builddeps  :
    - pkgconfig(libedit)
    - pkgconfig(xaw7)
setup      : |
    # This package requires two configure make passes,
    # The first to build the shared lib and the second
    # to build the executables.
    %configure --enable-cider \
               --enable-oldapps \
               --enable-openmp \
               --enable-xspice \
               --with-ngshared \
               --with-readline=no
    %make
build      : |
    %configure --enable-cider \
               --enable-openmp \
               --enable-xspice \
               --with-readline=no
    %make
install    : |
    %make_install
    # Sort out your build system
    install -Dm00755 $workdir/src/.libs/libngspice.so.0.0.2 $installdir/%libdir%/libngspice.so.0.0.2
    install -Dm00755 $workdir/src/.libs/libngspice.so.0 $installdir/%libdir%/libngspice.so.0
    install -Dm00755 $workdir/src/.libs/libngspice.so $installdir/%libdir%/libngspice.so
    install -Dm00644 ngspice.pc $installdir/usr/lib64/pkgconfig/ngspice.pc
    install -Dm00644 src/include/ngspice/sharedspice.h $installdir/usr/include/ngspice/sharedspice.h
check      : |
    %make check || :
