name       : ngspice
version    : '29'
release    : 2
source     :
    - https://kent.dl.sourceforge.net/project/ngspice/ng-spice-rework/29/ngspice-29.tar.gz : 8d6d0ffbc15f248eb6ec3bde3b9d1397fbc95cb677e1c6a14ff46065c7f95c4a
license    :
    - BSD-3-Clause
    - LGPL-2.1-or-later
component  : office
summary    : Mixed-Level, Mixed-Signal Circuit Simulator
description: |
    Ngspice is a mixed-level/mixed-signal circuit simulator. Its code is based on three open source software packages: Spice3f5, Cider1b1 and Xspice. It is the open source successor of these venerable packages. Many, many modifications, bug fixes and improvements have been added to the code, yielding a stable and reliable simulator. Therefore, besides being used as a standalone simulator, Ngspice has been incorporated into many projects.
builddeps  :
    - pkgconfig(xaw7)
setup      : |
    # This package requires two configure make passes,
    # The first to build the shared lib and the second
    # to build the executables.
    %configure --with-ngshared --enable-xspice
    %make
build      : |
    %configure --enable-xspice
    %make
install    : |
    %make_install
    # Sort out your build system
    install -Dm00755 $workdir/src/.libs/libngspice.so.0.0.0 $installdir/%libdir%/libngspice.so.0.0.0
    install -Dm00755 $workdir/src/.libs/libngspice.so.0 $installdir/%libdir%/libngspice.so.0
    install -Dm00755 $workdir/src/.libs/libngspice.so $installdir/%libdir%/libngspice.so
check      : |
    %make check
